name: Jekyll

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    steps:
      - uses: actions/checkout@v2
      - uses: Tyler887/jekyllbuild@1.3
      - uses: actions/upload-artifact@v2
        with:
          name: jekyll
          path: ./_site
