name: Jekyll Deployment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./_site
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@main
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: https://tyler887.github.io/fancade-lib
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
