name: Jekyll Deployment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Tyler887/JekyllBuild@1.1
      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./_site
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/upload-artifact@v2
